export const PLAYER_ASSETS = [
  { key: 'player-up', path: '/assets/sprites/player/character-up.png' },
  { key: 'player-up-left', path: '/assets/sprites/player/character-up-left.png' },
  { key: 'player-up-right', path: '/assets/sprites/player/character-up-right.png' },
  { key: 'player-down', path: '/assets/sprites/player/character-down.png' },
  { key: 'player-down-left', path: '/assets/sprites/player/character-down-left.png' },
  { key: 'player-down-right', path: '/assets/sprites/player/character-down-right.png' },
  { key: 'player-left', path: '/assets/sprites/player/character-left.png' },
  { key: 'player-left-left', path: '/assets/sprites/player/character-left-left.png' },
  { key: 'player-left-right', path: '/assets/sprites/player/character-left-right.png' },
  { key: 'player-right', path: '/assets/sprites/player/character-right.png' },
  { key: 'player-right-left', path: '/assets/sprites/player/character-right-left.png' },
  { key: 'player-right-right', path: '/assets/sprites/player/character-right-right.png' },
  { key: 'labcoat-up', path: '/assets/sprites/player/labcoat-up.png' },
  { key: 'labcoat-up-left', path: '/assets/sprites/player/labcoat-up-left.png' },
  { key: 'labcoat-up-right', path: '/assets/sprites/player/labcoat-up-right.png' },
  { key: 'labcoat-down', path: '/assets/sprites/player/labcoat-down.png' },
  { key: 'labcoat-down-left', path: '/assets/sprites/player/labcoat-down-left.png' },
  { key: 'labcoat-down-right', path: '/assets/sprites/player/labcoat-down-right.png' },
  { key: 'labcoat-left', path: '/assets/sprites/player/labcoat-left.png' },
  { key: 'labcoat-left-left', path: '/assets/sprites/player/labcoat-left-left.png' },
  { key: 'labcoat-right', path: '/assets/sprites/player/labcoat-right.png' },
  { key: 'labcoat-right-right', path: '/assets/sprites/player/labcoat-right-right.png' },
] as const
